--Reportdatabase must be on the same instance where ReportMigration tests are performed.
--Change the databasename of the reportserver that you are using for reportdeployment.
CREATE VIEW [Testing].[v_ReportsThatHaveSuccessfullyDeployed]
AS
SELECT [ItemID]
      ,[Path]
      ,[Name]
      ,[ParentID]
      ,[Type]
      ,[Content]
      ,[Intermediate]
      ,[SnapshotDataID]
      ,[LinkSourceID]
      ,[Property]
      ,[Description]
      ,[Hidden]
      ,[CreatedByID]
      ,[CreationDate]
      ,[ModifiedByID]
      ,[ModifiedDate]
      ,[MimeType]
      ,[SnapshotLimit]
      ,[Parameter]
      ,[PolicyID]
      ,[PolicyRoot]
      ,[ExecutionFlag]
      ,[ExecutionTime]
      ,[SubType]
      ,[ComponentID]
FROM [$(ReportingServicesDummy)].[dbo].[Catalog] WHERE [Type] = 2